###############################################################################
# This is bada's configuration.

version: 0.9

######################################################
## neural network 

# network definition
network_type: 0        # refer to neural_net/const.py
lstm: False

lstm_timestep: 20
lstm_lr: 0.00001        # 
cnn_lr:  0.001          # default of Adam is 0.001 

# normalize data
normalize_data: True

# training
# data_shuffle: True
validation_rate: 0.3
num_epochs: 50
batch_size: 16
num_outputs: 1
early_stopping_patience: 3
# tensorboard log dir
tensorboard_log_dir: logs/scalars/

# data augmentation
data_aug_flip: False
data_aug_bright: True
data_aug_shift: True

# input image size to the neural network
input_image_width: 160
input_image_height: 160
input_image_depth: 3

# steering data preprocessing
# - steering angle adjustment
steering_angle_scale: 5.0
# - steering wheel jitter tolerance
steering_angle_jitter_tolerance: 0.01
