# config file name
# - If you want to change it, make your own copy like <meaningful>.yaml
# - The config name will be postfixed to the neural network weight file name
# - update: separated configs
#neural_net: scout-bada-orchard-no-crop
#neural_net: scout-bada-orchard-bottom-half-crop
#neural_net: scout-bada-orchard-bottom-half-upper-half-crop
neural_net: scout-bada-orchard-area-crop

data_collection: scout-bada-orchard
run_neural: scout-bada-orchard
