# config file name
# - If you want to change it, make your own copy like <meaningful>.yaml
# - The config name will be postfixed to the neural network weight file name
# - update: separated configs
neural_net: scout-bada-orchard-bottom-half-upper-half-crop
data_collection: scout-bada-orchard
run_neural: scout-bada-orchard
