###############################################################################
# This is default configuration.

version: 0.92

# history
# 0.92: add brake ==> data format changed - data_collection
# 0.91: add image_width, height

######################################################
## data collection

# driving simulator
steering_angle_max: 450
steering_angle_tolerance: 0.015 # around 7.5 degree

# image cropping: True for legacy datasets. 
#                 False for new datasets.
crop: False

# vehicle name
vehicle_name: rover
# camera image topic 
camera_image_topic: /camera/image_raw
# vehicle control topic name
vehicle_control_topic: /rover
# p3d - current position and velocity
base_pose_topic: /mavros/global_position/local
# mavros cmd_vel topic
mavros_cmd_vel_topic: /mavros/setpoint_velocity/cmd_vel_unstamped

######################################################
## when training and running, cropping input image 

# crop (capture) area from a camera image
# - gazebo simulated camera resolution: 800x600
image_crop_x1: 0
image_crop_y1: 274
image_crop_x2: 799
image_crop_y2: 414

image_width: 800
image_height: 800